name: 'Setup Node and pnpm'
description: 'Setup Node.js with PNPM and install dependencies with proper caching'

inputs:
  checkout:
    description: 'Whether to checkout the repository'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      if: inputs.checkout == 'true'
      uses: actions/checkout@v6

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
        cache: pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile --prefer-offline
      shell: bash
