# This workflow runs every five minutes to check for a new manifest
name: Check for new manifest
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout D2AI
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1.4.2
        with:
          node-version: '14.x'

      - name: Install Yarn
        uses: bahmutov/npm-install@v1

      - name: Check for manifest update
        run: yarn manifest:check
        env:
          PAT: ${{ secrets.PAT }}
