# This workflow runs every five minutes to check for a new manifest
name: Check for new manifest
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.2
        with:
          node-version: '14.x'
      - uses: bahmutov/npm-install@v1
      - name: Download latest.json
        uses: andymckay/get-gist-action@0.1
        with:
          gistURL: ${{ secrets.GIST_URL }}
      - name: move from /tmp/latest.json to latest.json
        run: mv /tmp/latest.json latest.json
      - name: store latest for later
        run: echo ::set-output name=version::`cat latest.json`
        id: before
      - name: Check for manifest update
        run: yarn manifest:check
        env:
          PAT: ${{ secrets.PAT }}
      - name: store latest for later
        run: echo ::set-output name=version::`cat latest.json`
        id: after
      - name: output before/after
        run: |
          echo "BEFORE: ${{ steps.before.outputs.version }}"
          echo "AFTER: ${{ steps.after.outputs.version }}"
      - uses: popsiclestick/gist-sync-action@v1.0.0
        if: steps.before.outputs.version != steps.after.outputs.version
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: ${{ secrets.GIST_URL }}
          gist_title: latest.json
          github_file: latest.json
