# This workflow runs when a new manifest is detected by cron
name: New Manifest Detected
on:
  workflow_dispatch:
  repository_dispatch:
    types: [new-manifest-detected]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup
        uses: ./.github/actions/setup-pnpm
        with:
          checkout: 'false'

      - name: Generate new D2AI information
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: pnpm generate-data

      - name: porcelain check
        uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4
        id: D2AI-data
        with:
          base: HEAD
          filters: |
            changed:
              - '**'

      - name: Create Pull Request
        if: steps.D2AI-data.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          token: ${{ secrets.PAT }}
          commit-message: D2AI - Update All - Manifest v${{ github.event.client_payload.config.env.MANIFEST_VERSION }}
          committer: D2AI Bot <destinyitemmanager@gmail.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: '[D2AI] Manifest Update'
          body: |
            Manifest Update
            - Update All - Manifest v${{ github.event.client_payload.config.env.MANIFEST_VERSION }}
            - Auto-generated by [D2AI][1]

            [1]: https://github.com/DestinyItemManager/d2-additional-info
          branch: d2ai-manifest-v${{ github.event.client_payload.config.env.MANIFEST_VERSION }}
