# This workflow runs when a PR is merged or a new manifest is detected by cron
name: Pull Request Merge Flow
on:
  repository_dispatch:
    types: [new-manifest-detected]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout - D2AI
        uses: actions/checkout@v2
        with:
          path: 'd2ai'

      - name: Checkout - DIM
        uses: actions/checkout@v2
        with:
          repository: DestinyItemManager/DIM
          path: DIM

      - uses: actions/setup-node@v1.4.2
        with:
          node-version: '14.x'

      - uses: bahmutov/npm-install@v1
        with:
          working-directory: d2ai
        if: github.event == 'repository_dispatch'

      - name: Update D2AI with new manifest information
        if: github.event == 'repository_dispatch'
        run: |
          cd d2ai
          yarn manifest:get
          yarn generate-data

      - name: Create Pull Request (D2AI)
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: d2ai-config-update-${{ github.event.client_payload.config.env.MANIFEST_VERSION }}
          title: update configs - d2ai rules changed - ${{ github.event.client_payload.config.env.MANIFEST_VERSION }}
          committer: 'D2AI Bot <destinyitemmanager@gmail.com>'
          reviewer: 'delphiactual,sundevour'
          labels: 'd2ai,auto-pr'
        if: github.event == 'repository_dispatch'

      - name: Update DIM with new info from D2AI
        run: |
          cd DIM
          yarn install
          find src/data/d2/* -delete
          cp -f ../d2ai/output/* ./src/data/d2/

      - name: Create Pull Request (DIM)
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.PAT }}
          branch: d2ai-config-update-${{ github.sha }}
          title: update configs - d2ai rules changed - ${{ github.sha }}
          committer: 'D2AI Bot <destinyitemmanager@gmail.com>'
          reviewers: 'delphiactual,sundevour'
          labels: 'd2ai,auto-pr'
