# This workflow runs when a PR is merged
name: Pull Request Merge Flow
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout - D2AI
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_KEY }}
          path: 'd2ai'

      - name: Checkout - DIM
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_KEY }}
          repository: DestinyItemManager/DIM
          path: DIM

      - name: Install Hub
        uses: geertvdc/setup-hub@master

      - name: Install Node
        uses: actions/setup-node@v1.4.2
        with:
          node-version: '14.x'

      - name: Update DIM with new info from D2AI
        run: |
          cd DIM
          find src/data/d2/* -delete
          cp -f ../d2ai/output/* ./src/data/d2/

      - name: Check for new files (DIM)
        id: DIM-porcelain
        run: |
          cd DIM
          echo ::set-output name=porcelain::"$(git status --porcelain)"

      - name: Create Pull Request (DIM)
        if: steps.DIM-porcelain.outputs.porcelain
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'd2ai-config-update-${{ github.sha }}'
          COMMIT_MSG: 'update all - repo changed - ${{ github.sha }}'
        run: |
          cd DIM
          git config --global user.email "destinyitemmanager@gmail.com"
          git config --global user.name "DIM Config Bot"        
          git checkout -b $BRANCH_NAME
          git add -A
          git commit -m "$COMMIT_MSG"
          hub pull-request -p -r sundevour,delphiactual -m "d2ai automated build update" -m "$COMMIT_MSG"
