# This workflow runs when a PR is merged
name: Pull Request Merge Flow
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout - D2AI
        uses: actions/checkout@v2
        with:
          path: 'd2ai'

      - name: Checkout - DIM
        uses: actions/checkout@v2
        with:
          repository: DestinyItemManager/DIM
          path: 'DIM'

      - name: Checkout - D2AI-module
        uses: actions/checkout@v2
        with:
          repository: DestinyItemManager/d2ai-module
          path: 'd2ai-module'

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x

      - name: Install Node
        uses: actions/setup-node@v1.4.2
        with:
          node-version: '14.x'

      - name: Update DIM with new info from D2AI
        run: cd DIM && find src/data/d2/* -delete && cp -f ../d2ai/output/* ./src/data/d2/

      - name: Check for new files (DIM)
        id: DIM-porcelain
        run: cd DIM && echo ::set-output name=porcelain::"$(git status --porcelain)"

      - name: Create Pull Request (DIM)
        if: steps.DIM-porcelain.outputs.porcelain
        uses: peter-evans/create-pull-request@v2
        with:
          path: 'DIM'
          token: ${{ secrets.PAT }}
          commit-message: D2AI Build Update - ${{ env.GITHUB_SHA_SHORT }}
          committer: D2AI Bot <destinyitemmanager@gmail.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: '[D2AI] Build Update'
          body: |
            Build Update
            - Update All - D2AI Changed - https://github.com/DestinyItemManager/d2-additional-info/commit/${{ github.sha }}
            - Auto-generated by [D2AI][1]

            [1]: https://github.com/DestinyItemManager/d2-additional-info
          labels: d2ai, automated pr
          reviewers: delphiactual, sundevour
          branch: d2ai-build

      - name: Update D2AI-module with new info from D2AI
        run: cp -f d2ai/output/* d2ai-module/

      - name: Check for new files (D2AI-module)
        id: d2ai-module-porcelain
        run: cd d2ai-module && echo ::set-output name=porcelain::"$(git status --porcelain)"

      - name: Push missed changes D2AI-module
        if: steps.d2ai-module-porcelain.outputs.porcelain
        uses: delphiactual/github-push-action@master
        with:
          path: d2ai-module
          github_token: ${{ secrets.PAT }}
          commit_message: 'D2AI Build Update - ${{ env.GITHUB_SHA_SHORT }}'
          user_email: 'destinyitemmanager@gmail.com'
          user_name: 'D2AI Bot'
          branch: master
