# This workflow runs when a PR is requested
name: Pull Request Flow
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout D2AI
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}

      - name: Install Node
        uses: actions/setup-node@v1.4.2
        with:
          node-version: '14.x'

      - name: yarn install
        uses: bahmutov/npm-install@v1

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x

      - name: Compile Typescript
        run: yarn build

      - name: Get D2 Manifest
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 2
          max_attempts: 3
          command: yarn manifest:get
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Generate Data
        run: yarn generate-data

      - name: Check for new files
        id: data
        run: echo ::set-output name=porcelain::"$(git status --porcelain)"

      - name: Commit other updated values
        if: steps.data.outputs.porcelain
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: other updates from manifest
          commit_user_name: D2AI Bot
          commit_user_email: destinyitemmanager@gmail.com
          commit_author: D2AI Bot <destinyitemmanager@gmail.com>
