# This workflow runs when a PR is requested
name: Pull Request Flow
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout D2AI
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn

      - name: Install
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@3.1.0

      - name: Compile Typescript
        run: yarn build

      - name: Get D2 Manifest
        uses: nick-invision/retry@v2.0.0
        with:
          timeout_minutes: 2
          max_attempts: 3
          command: yarn manifest:get
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Generate Data
        run: yarn generate-data

      - name: Check for new files
        id: data
        run: echo ::set-output name=porcelain::"$(git status --porcelain)"

      - name: Please run `yarn generate-data`
        if: steps.data.outputs.porcelain
        uses: github-actions-up-and-running/pr-comment@v1.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: Please run `yarn i18n`

      - name: Fail the Build
        if: steps.data.outputs.porcelain
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Please run `yarn generate-data`')
