# This workflow runs when a PR is requested
name: Pull Request Flow
on:
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.2
        with:
          node-version: '14.x'
      - uses: bahmutov/npm-install@v1
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x
      - run: yarn manifest:get
      - run: yarn generate-data
      - name: Push changes
        uses: delphiactual/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: 'you dropped these'
          user_email: 'destinyitemmanager@gmail.com'
          user_name: 'DIM D2AI Bot'
          branch: ${{ env.GITHUB_HEAD_REF_SLUG }}
