# This workflow runs when a PR is requested
name: Pull Request Flow
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths: ['src/**', 'data/**', '.github/workflows/PR.yml', 'package.json', 'yarn.lock']

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event.pull_request.draft == false
    env:
      fork_pr: ${{ github.event.pull_request.head.repo.full_name != github.repository }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout D2AI
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: yarn

      - name: Install
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Compile Typescript
        run: yarn build

      - name: Get D2 Manifest
        uses: nick-invision/retry@v2.0.0
        with:
          timeout_minutes: 2
          max_attempts: 3
          command: yarn manifest:get
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Generate Data
        id: data
        run: |
          yarn generate-data
          echo ::set-output name=newdata::"$(git status --porcelain)"

      - name: Commit other updated values
        if: steps.data.outputs.newdata && !env.fork_pr
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: other updates from manifest
          commit_user_name: D2AI Bot
          commit_user_email: destinyitemmanager@gmail.com
          commit_author: D2AI Bot <destinyitemmanager@gmail.com>

      - name: Please run `yarn generate-data`
        if: steps.data.outputs.newdata && env.fork_pr
        uses: github-actions-up-and-running/pr-comment@v1.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: Please run `yarn generate-data`

      - name: Fail the Build
        if: steps.data.outputs.newdata && env.fork_pr
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Please run `yarn generate-data`')
