# This workflow runs when a PR is requested
name: Pull Request Flow
on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout D2AI
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1.4.2
        with:
          node-version: '14.x'

      - name: Install Yarn
        uses: bahmutov/npm-install@v1

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x

      - name: Compile Typescript
        run: yarn build

      - name: Get D2 Manifest
        run: yarn manifest:get

      - name: Generate Data
        run: yarn generate-data

      - name: Push missed changes to D2AI
        uses: delphiactual/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: 'you dropped these'
          user_email: 'destinyitemmanager@gmail.com'
          user_name: 'DIM D2AI Bot'
          branch: ${{ env.GITHUB_HEAD_REF_SLUG }}
