name: Workflow Lint

on:
  pull_request:
    paths: ['.github/workflows/**']
  push:
    branches: [master]
    paths: ['.github/workflows/**']

permissions:
  contents: read
  pull-requests: write

jobs:
  actionlint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run actionlint
        uses: reviewdog/action-actionlint@320fcdd9c860767cf17fab3b20e22e739d5d02b8 # v1
        with:
          reporter: github-pr-review
          fail_level: error
